# SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, ROUND((100-P.DISCOUNT_RATE)/100*30*C.DAILY_FEE) as FEE
# FROM CAR_RENTAL_COMPANY_CAR as C
# LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as H 
#     on C.CAR_ID = H.CAR_ID
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as P
#     ON C.CAR_TYPE = P.CAR_TYPE
# WHERE C.CAR_TYPE in ('세단', 'SUV')
#     AND P.DURATION_TYPE = '30일 이상'
#     AND (H.CAR_ID IS NULL or H.START_DATE > '2022-11-30' or H.END_DATE < '2022-11-01')
# HAVING FEE >= 500000 and FEE < 2000000
# ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;

SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, FLOOR((100 - P.DISCOUNT_RATE) / 100.0 * 30 * C.DAILY_FEE) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND P.DURATION_TYPE = '30일 이상'
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        WHERE H.CAR_ID = C.CAR_ID
          AND H.START_DATE <= '2022-11-30'
          AND H.END_DATE >= '2022-11-01'
    )
    AND FLOOR((100 - P.DISCOUNT_RATE) / 100.0 * 30 * C.DAILY_FEE) >= 500000
    AND FLOOR((100 - P.DISCOUNT_RATE) / 100.0 * 30 * C.DAILY_FEE) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;
