-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) as YEAR, MONTH(OS.SALES_DATE) as MONTH, UI.GENDER, COUNT(DISTINCT UI.USER_ID) as USERS
FROM USER_INFO as UI
JOIN ONLINE_SALE as OS ON UI.USER_ID = OS.USER_ID
GROUP BY YEAR, MONTH, UI.GENDER
HAVING UI.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, UI.GENDER;