-- 코드를 입력하세요
SELECT 
    YEAR(OS.SALES_DATE) as YEAR, 
    MONTH(OS.SALES_DATE) as MONTH, 
    COUNT(DISTINCT OS.USER_ID) as PURCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) as PUCHASED_RATIO
FROM USER_INFO AS UI
JOIN ONLINE_SALE AS OS ON UI.USER_ID = OS.USER_ID 
WHERE YEAR(UI.JOINED) = 2021 and YEAR(OS.SALES_DATE) IS NOT NULL
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;