-- 코드를 작성해주세요
SELECT 
    B.YEAR as YEAR, B.MAX_SIZE-A.SIZE_OF_COLONY as YEAR_DEV, A.ID as ID
    FROM ECOLI_DATA as A
JOIN 
    (SELECT MAX(SIZE_OF_COLONY) as MAX_SIZE,YEAR(DIFFERENTIATION_DATE) as YEAR from ECOLI_DATA GROUP BY YEAR) as B 
    ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY B.YEAR, YEAR_DEV;