-- 코드를 입력하세요
SELECT FP.CATEGORY, FP.PRICE as MAX_PRICE, FP.PRODUCT_NAME 
FROM FOOD_PRODUCT as FP 
JOIN (SELECT CATEGORY, MAX(PRICE) as MAXP FROM FOOD_PRODUCT GROUP BY CATEGORY) as MAX_FP 
ON MAX_FP.CATEGORY = FP.CATEGORY and MAX_FP.MAXP = FP.PRICE
WHERE FP.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY FP.PRICE DESC;